#!/usr/bin/osascript
on run argv
    set args to ""
    repeat with arg in argv
        set args to args & " " & arg
    end repeat
    set mycommand to "zsh -c \"" & args & " zsh\""
    tell application "iTerm"
        activate
        set myterm to (make new terminal)
        tell myterm
            set mysession to (make new session at the end of sessions)
            tell mysession
                exec command mycommand
            end tell
        end tell
    end tell
end run
